# Generated by Django 3.1.4 on 2021-03-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_category_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
